version: '3.3'
services:
  redis_master:
    image: redis
    container_name: redis_master
    restart: always
    ports:
     - '6379'
    volumes:
      - './data/master:/data'
  redis_slave:
    image: redis
    container_name: redis_slave
    restart: always
    depends_on:
      - redis_master
    command: redis-server --slaveof redis_master 6379
    volumes:
      - './data/slave:/data'
    ports:
      - '6379'
volumes:
  data:
